language: node_js
node_js:
- 9
cache:
  directories:
  - node_modules # NPM packages
install:
  - npm install
  - pip install --user awscli
script: npm run build
deploy:
  provider: s3
  access_key_id: AKIAJZPYE7KLBFOUYRGA
  secret_access_key:
    secure: w97n2L9hUya+RVmtfqLLAkI3CPQAm0A898eduppYdYzioVylfZzaKWMoYs3fEVQyCJguiJb/4F7/uMdAPlrhcPpedSRAjU9Q9Q7fKGlZ7/lbvnUSi73H8A4HdI1CPmMFMmrLDozB7E5x9aK/DKPuj/2NLYM7dYblhZcE6Sy6JKY8mplykhsUiUVvr7W2bkVyDrig0wE4SlE68YeYNePk3Zp2rgv6mOG0NQ8LdGX3MKhflUEm/jOpDKn2KGdeBadbBx9/CdrYaewK6tw3ld+6MnHuYAxa7IFAv9Uc3jPVqQGTr9M98RrLYG+6Gp85+nPGsyG9HcKXt7zdbpLKdRzU5HXNv4QL21DcFRW8YThOYHwsQIXlJGfVC/OgRo+GtkoAMeNbdWGdVYFIBDiza+OklTnA4dLYpnmE4y/L0oE5/QM1RdqxG7LaQ4gPWHGPBV7GCkm50zSfLJtSoLG181Pvr9Z2Hu63e/5ilGPuVWFoVqiJq4zUo89mO/K+OcsPCQc3jogSzPzBDzNCOZtf2z2dIQgfKVYUZMDrDM3UPe15WvcYHQDRsfLO4RplIDLsgu8W4AmnedjnDAuOGMjOiyBRHeCmpq6Xd7+Csoa3YILU6AHrFNSwFOkYeB6NrkK43VR4dpqA46hPlkj2jvQYZ4B7SzVB4zxnWn0QEs80Q4/AK+Y=
  bucket: www.traintickets.to
  local-dir: build/
  skip_cleanup: true
  region: eu-west-1
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id EJPXTPGNQTGCE --paths "/*"