sudo: false
language: node_js
node_js:
  - "6.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - NODE_ENV=production npm run deploy

after_success:
  - npm run codecov
