language: node_js
node_js:
- 9
cache:
  directories:
  - node_modules # NPM packages
install:
  - npm install
  - pip install --user awscli
script: npm run build
deploy:
  provider: script
  script: aws s3 sync ./build/ s3://www.traintickets.to/ --delete  --region eu-west-1
  local-dir: build/
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"